Require two releng signoffs for changes to permissions
mozilla-releng/balrog pull request #2528
Opened 2022-05-16 15:10 UTC by gabrielbusta

#2194

2022-05-16 15:15 UTC, gabrielBusta commented
I tried to implement two admin sign-offs. Because that moves us from looking at "roles" when checking sign-offs to looking at "permissions" it required some refactoring in the back-end and UI. I ended up hard-coding 2 "releng" sign-offs. Before this lands in production we need to make sure that nobody currently has that role that shouldn't.

2022-05-16 16:03 UTC, jcristau requested changes
I'm a bit unhappy about hardcoding a specific role here (iirc we don't do that anywhere else). More importantly, this will break local setups where there may not be 2 users with that role.

Finally, before we merge anything we'll need to add tests.

2022-05-20 18:19 UTC, gabrielBusta commented
Yea. It is not ideal. We could add configuration parameter for the number of "releng" sign-offs and set it to 1 when running locally. Is it worth it landing this hacky fix so the VPN team can self-serve updates?

2026-01-22 15:08 UTC, bhearsum commented
Closing for inactivity; already cross linked to https://github.com/mozilla-releng/balrog/issues/2194.

2026-01-22 15:08 UTC, closed without merging