show release alias on rules page
mozilla-releng/balrog pull request #3023
Opened 2023-10-19 16:14 UTC by nazarenegena

This PR attempts to fix the issue #1138.
I have added the alias for the releases on the rules page. When you hover on the specific rule you can see it's alias.
however, since most of the releases' alias is 'null' I have left the '#' in its place. 
Is this the expected solution?

2023-10-24 18:01 UTC, bhearsum requested changes
Unfortunately, this does not address the issue. What we'd like is for a change on the Releases page to show rule alias' instead of rule ids. For example, in this screenshot:
![image](https://github.com/mozilla-releng/balrog/assets/49649/f2cca7f0-1ce0-4242-b575-02a21b2a5bb4)

The `56` should be `firefox-release-localtest`, `145` should be `firefox-release`, and `585` should be `firefox-release-cdntest`.

This will require changes to https://github.com/mozilla-releng/balrog/blob/main/ui/src/components/ReleaseCard/index.jsx and possibly some of the data passed to it.

2023-10-24 19:47 UTC, nazarenegena commented
Cool, thanks for the update. I will work on it.

2023-10-27 11:46 UTC, nazarenegena commented
Updated the releases page to now show rule alias instead of rule ids

2023-10-27 14:32 UTC, bhearsum requested changes

2023-10-27 14:32 UTC, bhearsum commented on ui/src/components/ReleaseCard/index.jsx
> +                                ruleInfo.channel ? `- ${ruleInfo.channel}` : ''
This is not what we want either. The alias is a property of the `rule`. I can see why you're struggling though - the alias is not returned by the `/releases` endpoint, so the data you need is not even present.

I suggest you fetch the rules (similar to how we do on the rules page: https://github.com/mozilla-releng/balrog/blob/ca55f9aa6aa15647370a841d8827e1e724ab8813/ui/src/views/Rules/ListRules/index.jsx#L164), and use that to find the alias for each ruleId.

2023-10-27 20:45 UTC, nazarenegena commented
Cool, Noted. Will work on this.

2023-11-02 14:56 UTC, nazarenegena commented
I have updated the alias for the releases on the rules page
As for the rules that don't have an alias I have used their rule id

2023-11-02 19:59 UTC, bhearsum requested changes
The changes look good - can you please fix the lint issues before we merge, though?

2023-11-03 09:33 UTC, nazarenegena commented
Working on the fixes.

2023-11-03 20:00 UTC, nazarenegena commented
I have fixed the lint issues

2023-11-13 15:52 UTC, bhearsum approved these changes
Thank you!

2023-11-13 15:53 UTC, bhearsum commented
@nazarenegena - Unfortunately, this now has conflicts with the latest `main`. Can you update your branch? Feel free to ping me on Matrix if you need help with that.

2023-11-14 04:39 UTC, nazarenegena commented
Cool, let me update my branch.

2023-11-14 17:54 UTC, nazarenegena commented
conflicts resolved.

2023-11-14 20:14 UTC, bhearsum approved these changes
This looks great now - thank you!

2023-11-14 20:14 UTC, merged

2023-11-15 07:28 UTC, nazarenegena commented
you're welcome.