make the emergency shutoff button unclickeable when disabled
mozilla-releng/balrog pull request #3028
Opened 2023-10-22 03:51 UTC by MelakuAlehegn

This PR is for a fix for #2610 
+ Button clickable and enabled at first
+ Button gets disabled and click wont redo the disabling again, like it used to.
+ Button becomes disabled and unclickable after disabled updates

Here I have selected a product: Fennect: beta 
![image](https://github.com/mozilla-releng/balrog/assets/49185991/14cab0fc-09ec-47e5-bfb2-9616c0a4c368)

Enabled button: Clickable at first
![enabled button](https://github.com/mozilla-releng/balrog/assets/49185991/13cb5093-b785-4903-baf2-0bd9908fd9ff)

Disabling updates
![disabling](https://github.com/mozilla-releng/balrog/assets/49185991/9cfb3abd-a8cd-41e9-94da-e3e69733fee5)

Disabled and button unclickable
![disabled and unclickable](https://github.com/mozilla-releng/balrog/assets/49185991/66e8773a-1b12-46ca-aa0c-820496e1a17c)

2023-10-23 13:56 UTC, allan-silva commented on agent/run.sh
This changes are hitting some script files not related with the issue. Seems like file metadata was changed or something like this.

![image](https://github.com/mozilla-releng/balrog/assets/9947646/b68ca6f8-95bf-421e-9194-c78863d88769)

2023-10-23 16:12 UTC, MelakuAlehegn commented on agent/run.sh
@allan-silva,  I have only changed ui/src/views/Rules/ListRules/index.jsx file, but somehow this files have been added too.

2023-10-23 18:52 UTC, MelakuAlehegn commented
@gabrielBusta @bhearsum Can you take a look at my solution to this issue please?

2023-10-23 20:18 UTC, MelakuAlehegn commented on agent/run.sh
Should I create another PR with a different branch name for this issue?, seems like this could be resolved if I only stages the index.js file to git so that the files wouldn't get pushed.

2023-10-23 20:45 UTC, bhearsum commented on agent/run.sh
If that's the easiest way for you to get a clean PR, please go ahead. It is also possible to revert the changes from your current branch.

2023-10-24 03:59 UTC, MelakuAlehegn commented
@bhearsum Can you give suggestions on this failing test? It seems related to the commit hash.

2023-10-24 13:10 UTC, bhearsum commented
> @bhearsum Can you give suggestions on this failing test? It seems related to the commit hash.

It looks like it was an intermittent issue - a rebuild fixed it.

2023-10-24 16:40 UTC, gabrielBusta requested changes
Thanks for the contribution @MelakuAlehegn.

The changes you're seeing are changes to the file permissions in the Git repository. 

`100755` means the file is executable.

`100644` means the file is **not** executable.

To restore the files you could run this command on each of the files with the modified permissions:

`git restore --source=2181f9233850bcefd42a25b862d0f9a5c8083225 --staged --worktree <filename>`

This approach will restore the file's state (including its permissions) to [2181f92](https://github.com/MelakuAlehegn/balrog/commit/2181f9233850bcefd42a25b862d0f9a5c8083225) (which is the commit your changes are based on), and you can then commit the change as you usually would.

```
(balrog) ➜  balrog git:(emergency-shutoff-button) ✗ git restore --source=2181f9233850bcefd42a25b862d0f9a5c8083225 --staged --worktree maintenance/pin.sh 
(balrog) ➜  balrog git:(emergency-shutoff-button) ✗ git status -v
On branch emergency-shutoff-button
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   maintenance/pin.sh

diff --git a/maintenance/pin.sh b/maintenance/pin.sh
old mode 100644
new mode 100755
```

2023-10-24 17:24 UTC, MelakuAlehegn commented
> Thanks for the contribution @MelakuAlehegn.
> 
> The changes you're seeing are changes to the file permissions in the Git repository.
> 
> `100755` means the file is executable.
> 
> `100644` means the file is **not** executable.
> 
> To restore the files you could run this command on each of the files with the modified permissions:
> 
> `git restore --source=2181f9233850bcefd42a25b862d0f9a5c8083225 --staged --worktree <filename>`
> 
> This approach will restore the file's state (including its permissions) to [2181f92](https://github.com/MelakuAlehegn/balrog/commit/2181f9233850bcefd42a25b862d0f9a5c8083225) (which is the commit your changes are based on), and you can then commit the change as you usually would.
> 
> ```
> (balrog) ➜  balrog git:(emergency-shutoff-button) ✗ git restore --source=2181f9233850bcefd42a25b862d0f9a5c8083225 --staged --worktree maintenance/pin.sh 
> (balrog) ➜  balrog git:(emergency-shutoff-button) ✗ git status -v
> On branch emergency-shutoff-button
> Changes to be committed:
>   (use "git restore --staged <file>..." to unstage)
>         modified:   maintenance/pin.sh
> 
> diff --git a/maintenance/pin.sh b/maintenance/pin.sh
> old mode 100644
> new mode 100755
> ```

@gabrielBusta I have changed the file permissions back.

2023-10-24 18:46 UTC, gabrielBusta commented
Thanks @MelakuAlehegn, I see the issue has been resolved on a lot of the files.

I still see permission changes on these files that should be reverted:

1. `agent/run.sh`
2. `scripts/run.sh`
3. `scripts/test-rules.py`
4. `src/auslib/blobs/apprelease.py`
5. `src/auslib/blobs/base.py`
6. `taskcluster/docker/skopeo/push_image.sh`
7. `tests/blobs/test_apprelease.py`
8. `ui/scripts/deploy`

2023-10-25 04:05 UTC, MelakuAlehegn commented
@gabrielBusta I have reverted the permission changes for all files on this commit. Please take a look. Thanks

2023-10-25 09:22 UTC, MelakuAlehegn commented
> @gabrielBusta I have reverted the permission changes for all files on this commit. Please take a look.

@bhearsum

2023-10-25 12:27 UTC, allan-silva approved these changes
I made tests on `MelakuAlehegn:emergency-shutoff-button`, LGTM.

Thanks!

2023-10-25 16:51 UTC, MelakuAlehegn commented
> I made tests on `MelakuAlehegn:emergency-shutoff-button`, LGTM.
> 
> Thanks!

Thanks @allan-silva ,

2023-10-25 16:59 UTC, gabrielBusta approved these changes

2023-10-25 17:00 UTC, gabrielBusta commented
Looks great :)

Thanks @MelakuAlehegn

2023-10-25 17:01 UTC, merged