added product url param to required signoffs page
mozilla-releng/balrog pull request #3030
Opened 2023-10-24 12:46 UTC by nazarenegena

This attempts to address issue #1144 .
 made required signoffs page accept "product" url param.

2023-10-25 14:04 UTC, bhearsum requested changes
The changes look fine, but there's some lint issues that need to be fixed before we can merge this. Nice work!

2023-10-26 09:22 UTC, nazarenegena commented
Cool, fixing this.

2023-10-27 10:35 UTC, nazarenegena commented
The lint issues have been resolved.

2023-10-27 14:22 UTC, bhearsum approved these changes

2023-10-27 14:22 UTC, merged