log: avoid crashing when a log entry includes a non-JSON-serializable object
mozilla-releng/balrog pull request #3066
Opened 2023-11-28 17:41 UTC by jcristau

When enabling all debug logging we end up with fairly arbitrary objects in log messages.  Default to the object's `__str__` method in that case.

Note this is fairly arbitrary, I could be convinced to use `repr` instead.  I've seen stuff like `bytes`, `type`, `Response` in extra logging data from our dependencies, which all break with plain `json.dumps`.

2023-11-29 18:09 UTC, gbrownmozilla requested changes
https://github.com/mozilla-releng/balrog/blob/main/agent/src/balrogagent/log.py#L105 looks very similar ... can we do the same thing there?

2023-11-29 18:09 UTC, gbrownmozilla commented on src/auslib/log.py
> +        return json.dumps(out, default=str)
I don't have a strong opinion on `str` vs `repr`. `str` seems fine.

2023-11-30 13:09 UTC, jcristau commented
Good catch, updated to include the agent.

2023-11-30 15:23 UTC, gbrownmozilla approved these changes

2023-11-30 15:24 UTC, merged